# Generated by Django 6.0.6 on 2026-07-01 14:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('price_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('is_custom_request', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, help_text='For order/status notifications', max_length=254)),
                ('address', models.TextField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('advance_required', models.BooleanField(default=False)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('advance_received', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('cod_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('bkash', 'Manual bKash'), ('nagad', 'Manual Nagad')], max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=64)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('payment_verified', models.BooleanField(default=False)),
                ('fraud_check_result', models.JSONField(blank=True, default=dict)),
                ('steadfast_consignment_id', models.CharField(blank=True, max_length=64)),
                ('steadfast_tracking_code', models.CharField(blank=True, max_length=64)),
                ('steadfast_status', models.CharField(blank=True, max_length=32)),
                ('courier_submitted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('confirmed', 'Confirmed'), ('in_production', 'In production'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Bengali name shown to customer', max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('category', models.CharField(choices=[('book', 'Book'), ('box', 'Box'), ('pen', 'Pen'), ('mirror', 'Mirror'), ('dupatta', 'Dupatta')], max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('allows_individual_purchase', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomOrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('priced', 'Priced'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_request', to='app.cartitem')),
            ],
        ),
        migrations.CreateModel(
            name='CustomOrderReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='custom_requests/')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_images', to='app.customorderrequest')),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Set once the cart item becomes part of a placed order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.order'),
        ),
        migrations.CreateModel(
            name='InsideDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_image', models.ImageField(upload_to='inside/')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inside_designs', to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='ColorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. maroon, ivory, black (Bengali)', max_length=80)),
                ('base_image', models.ImageField(help_text='Plain item in this color', upload_to='colors/')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='app.product')),
            ],
            options={
                'ordering': ['product', 'name'],
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='app.product'),
        ),
        migrations.CreateModel(
            name='StaticDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static_designs/')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_designs', to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='ToppingDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('corner', 'Corner'), ('center', 'Center')], max_length=10)),
                ('image', models.ImageField(help_text='Transparent PNG overlay', upload_to='toppings/')),
                ('pos_x', models.FloatField(default=0, help_text='X offset (px or %) on the base image')),
                ('pos_y', models.FloatField(default=0, help_text='Y offset (px or %) on the base image')),
                ('scale', models.FloatField(default=1.0, help_text='Scale factor for the overlay')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='app.product')),
            ],
            options={
                'ordering': ['product', 'placement'],
            },
        ),
        migrations.CreateModel(
            name='DupattaOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lace_type', models.CharField(choices=[('single', 'Single lace'), ('four', 'Four lace')], max_length=10)),
                ('text_lines', models.PositiveSmallIntegerField(default=0, help_text='Number of text lines')),
                ('preview_image', models.ImageField(upload_to='dupatta/')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dupatta_options', to='app.product')),
            ],
            options={
                'ordering': ['lace_type', 'text_lines'],
                'constraints': [models.UniqueConstraint(fields=('product', 'lace_type', 'text_lines'), name='unique_dupatta_combo')],
            },
        ),
    ]
