# Generated by Django 6.0.6 on 2026-07-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cartitem_product_prebuiltcombo_comboimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('layered', 'Layered (color + corner + center, e.g. book/box)'), ('gallery', 'Gallery (pick one design, e.g. pen/mirror)'), ('dupatta', 'Dupatta (lace + lines lookup)'), ('simple', 'Simple (buy as-is or pick one design)')], default='simple', help_text='How this product is customized', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, help_text='Group label shown to customers, e.g. বই, আতর, তসবিহ', max_length=40),
        ),
    ]
