# Generated by Django 6.0.6 on 2026-07-02 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_backfill_product_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='division',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='is_repeat_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='thana',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='order',
            name='uid',
            field=models.CharField(blank=True, db_index=True, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(help_text='Street / house / road'),
        ),
        migrations.CreateModel(
            name='ConfigurationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='config_images/')),
                ('active', models.BooleanField(default=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_images_center', to='app.toppingdesign')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.coloroption')),
                ('corner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_images_corner', to='app.toppingdesign')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_images', to='app.product')),
            ],
        ),
    ]
