# Generated by Django 6.0.6 on 2026-07-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_district_order_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp number for order confirmation call', max_length=20),
        ),
    ]
