# Generated by Django 6.0.6 on 2026-07-02 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Referenced as [IMAGE: key]', max_length=60, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_media/')),
                ('album_url', models.URLField(blank=True, help_text='External album link for [ALBUM: key]')),
                ('caption', models.CharField(blank=True, max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Anonymous browser token', max_length=64)),
                ('customer_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('bot', 'Bot handling'), ('waiting_admin', 'Waiting for admin'), ('admin', 'Admin handling'), ('closed', 'Closed')], default='bot', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('bot', 'Bot'), ('admin', 'Admin'), ('system', 'System')], max_length=10)),
                ('text', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('album_url', models.URLField(blank=True)),
                ('read_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.chatsession')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
