# Generated by Django 6.0.6 on 2026-07-02 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_chatmedia_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmedia',
            name='album_url',
            field=models.URLField(blank=True, help_text='External album link (optional)'),
        ),
        migrations.AlterField(
            model_name='chatmedia',
            name='key',
            field=models.SlugField(help_text='Referenced as [IMAGE: key] / [ALBUM: key]', max_length=60, unique=True),
        ),
        migrations.CreateModel(
            name='ChatMediaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chat_media/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.chatmedia')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
