# Generated by Django 6.0.6 on 2026-07-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_botconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmedia',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Sent when the customer asks for a photo without specifying which'),
        ),
    ]
