# Generated by Django 6.0.6 on 2026-07-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_chatmedia_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='more_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
