# Generated by Django 6.0.6 on 2026-07-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_chatmessage_images_chatmessage_more_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preview_ratio',
            field=models.CharField(choices=[('1 / 1', 'Square'), ('9 / 12', 'Book (tall 9:12)'), ('12 / 10', 'Box (wide 12:10)')], default='1 / 1', help_text='Shape of the live preview box', max_length=12),
        ),
    ]
