# Generated by Django 6.0.6 on 2026-07-14 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_product_preview_ratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Bengali label shown on the tile', max_length=80)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_categories/')),
                ('link', models.CharField(blank=True, help_text='Where the tile goes, e.g. /shop?category=বই', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Home categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('hero_title', models.CharField(blank=True, max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, max_length=300)),
                ('band_image', models.ImageField(blank=True, help_text="Image in the 'customize' feature band", null=True, upload_to='site/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price for a strike-through discount (optional)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Detail-page description (Bengali)'),
        ),
        migrations.AddField(
            model_name='product',
            name='home_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Ordering within homepage sections (lower first)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in Featured Products on the homepage'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Show in Popular Products on the homepage'),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='track_stock',
            field=models.BooleanField(default=False, help_text='Enforce stock: block add-to-cart when 0'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt', models.CharField(blank=True, max_length=140)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.product')),
            ],
            options={
                'ordering': ['-is_primary', 'order', 'id'],
            },
        ),
    ]
