# Generated by Django 6.0.6 on 2026-07-15 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_homecategory_sitesettings_product_compare_at_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. উপকরণ, সাইজ, যা যা থাকছে', max_length=80)),
                ('value', models.CharField(max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='app.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
