# Generated by Django 6.0.6 on 2026-07-16 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/orig/')),
                ('display', models.ImageField(blank=True, upload_to='gallery/display/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='gallery/thumb/')),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('alt', models.CharField(blank=True, max_length=160)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='chatmediaimage',
            name='media',
        ),
        migrations.CreateModel(
            name='GalleryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Bengali label shown to customers', max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('is_bot_default', models.BooleanField(default=False, help_text='Bot links here when a customer asks for a photo without specifying')),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.galleryphoto')),
                ('photos', models.ManyToManyField(blank=True, related_name='tags', to='app.galleryphoto')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='ChatMedia',
        ),
        migrations.DeleteModel(
            name='ChatMediaImage',
        ),
    ]
