# Generated by Django 6.0.6 on 2026-07-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_galleryphoto_remove_chatmediaimage_media_gallerytag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='chat_uploads/'),
        ),
    ]
