# Generated by Django 6.0.6 on 2026-07-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_chatmessage_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customize_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Position in the /customize picker. Lower shows first.'),
        ),
        migrations.AddField(
            model_name='product',
            name='exclusive_group',
            field=models.CharField(blank=True, help_text="Products sharing this group cannot be selected together in the configurator (e.g. 'nikahnama' on book, frame, thumb). Blank = no restriction.", max_length=40),
        ),
    ]
