# Generated by Django 6.0.6 on 2026-07-17 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_product_customize_order_product_exclusive_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Shown to the customer, e.g. বরের নাম / এখানে কি বসবে?', max_length=120)),
                ('placeholder', models.CharField(blank=True, help_text='Optional hint', max_length=120)),
                ('required', models.BooleanField(default=True, help_text='Required fields block the confirm button')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_fields', to='app.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
