# Generated by Django 6.0.6 on 2026-07-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_productfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='country',
            field=models.CharField(blank=True, help_text='2-letter ISO code (e.g. bd). Blank = META DEFAULT_COUNTRY.', max_length=2),
        ),
        migrations.AddField(
            model_name='lead',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="Meta 'db' match key", null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='external_id',
            field=models.CharField(blank=True, help_text="Your own customer/lead ID for Meta 'external_id'. Blank = phone/email.", max_length=100),
        ),
    ]
