# Generated by Django 6.0.6 on 2026-07-18 07:19

from django.db import migrations, models


def mark_existing_seen(apps, schema_editor):
    # Existing orders predate the feature — treat them as already seen so the
    # badge/sound only fires for genuinely new orders from now on.
    Order = apps.get_model('app', 'Order')
    Order.objects.update(admin_seen=True)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_lead_country_lead_date_of_birth_lead_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_seen, migrations.RunPython.noop),
    ]
