# Generated by Django 6.0.6 on 2026-07-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prebuiltcombo',
            name='preset_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
