# Generated by Django 6.0.6 on 2026-07-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_combofield'),
    ]

    operations = [
        migrations.AddField(
            model_name='prebuiltcombo',
            name='category',
            field=models.CharField(blank=True, help_text='Shown on the card and used by the /products filter, e.g. দুপাট্টা', max_length=60),
        ),
    ]
