# Generated by Django 6.0.6 on 2026-07-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_prebuiltcombo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total cost to fulfil this order. Blank = not costed yet.', max_digits=10, null=True),
        ),
    ]
