# Generated by Django 6.0.6 on 2026-07-22 15:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_order_cost_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraConsignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=40)),
                ('consignment_id', models.CharField(blank=True, max_length=64)),
                ('tracking_code', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('cod_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('recipient_name', models.CharField(blank=True, max_length=100)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('recipient_address', models.CharField(blank=True, max_length=250)),
                ('item_description', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_consignments', to='app.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
