# Generated by Django 6.0.6 on 2026-07-26 15:45

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_order_meta_client_ip_order_meta_fbc_order_meta_fbp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=32, unique=True)),
                ('visitor_id', models.CharField(db_index=True, max_length=32)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('current_path', models.CharField(blank=True, max_length=200)),
                ('entry_path', models.CharField(blank=True, max_length=200)),
                ('exit_path', models.CharField(blank=True, max_length=200)),
                ('pageviews', models.PositiveIntegerField(default=0)),
                ('events', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(blank=True, max_length=40)),
                ('device', models.CharField(blank=True, max_length=10)),
                ('is_new_visitor', models.BooleanField(default=True)),
                ('converted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.AddField(
            model_name='dailystat',
            name='bounced_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailystat',
            name='new_visitors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailystat',
            name='pageviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailystat',
            name='sessions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailystat',
            name='total_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DailyFunnelStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('step', models.CharField(max_length=32)),
                ('sessions', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'step')},
            },
        ),
        migrations.CreateModel(
            name='DailyPageStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('path', models.CharField(max_length=200)),
                ('views', models.PositiveIntegerField(default=0)),
                ('sessions', models.PositiveIntegerField(default=0)),
                ('entries', models.PositiveIntegerField(default=0)),
                ('exits', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date', '-views'],
                'unique_together': {('date', 'path')},
            },
        ),
        migrations.CreateModel(
            name='DailySourceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('source', models.CharField(max_length=40)),
                ('sessions', models.PositiveIntegerField(default=0)),
                ('orders', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date', '-sessions'],
                'unique_together': {('date', 'source')},
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('session_id', models.CharField(db_index=True, max_length=32)),
                ('visitor_id', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('path', models.CharField(blank=True, max_length=200)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('props', models.JSONField(blank=True, default=dict)),
                ('combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.prebuiltcombo')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.product')),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['name', 'ts'], name='app_analyti_name_325364_idx'), models.Index(fields=['combo', 'ts'], name='app_analyti_combo_i_a70cdb_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyComboStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('carts', models.PositiveIntegerField(default=0)),
                ('orders', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='app.prebuiltcombo')),
            ],
            options={
                'ordering': ['-date', '-views'],
                'unique_together': {('date', 'combo')},
            },
        ),
    ]
