# Generated by Django 6.0.6 on 2026-07-27 09:46

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_visitorsession_dailystat_bounced_sessions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='cost_price',
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total money out, VAT included — what actually left the account.', max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='VAT portion already included in the amount (ads = 15% in BD).', max_digits=12)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='MFS/transfer charge paid on top of the amount.', max_digits=12)),
                ('account', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=10)),
                ('is_credit', models.BooleanField(default=False, help_text='Taken on credit — pay later, tracked in Dues.')),
                ('reference', models.CharField(blank=True, help_text='Invoice / trx id', max_length=80)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='finance/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orders', models.ManyToManyField(blank=True, related_name='expense_marks', to='app.order')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExpensePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Paid to the supplier.', max_digits=12)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='MFS/transfer charge paid on top — spent, but not credited to the due.', max_digits=12)),
                ('account', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.expense')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('kind', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Finance categories',
                'ordering': ['kind', 'order', 'name'],
                'unique_together': {('name', 'kind')},
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(limit_choices_to={'kind': 'expense'}, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='app.financecategory'),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Money received. For a courier payout this is the NET amount paid out — Steadfast already deducted delivery + its 1% COD fee.', max_digits=12)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='MFS/cash-out charge taken out of the amount received.', max_digits=12)),
                ('account', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=10)),
                ('reference', models.CharField(blank=True, help_text='Payout / trx id', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(limit_choices_to={'kind': 'income'}, on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='app.financecategory')),
                ('orders', models.ManyToManyField(blank=True, related_name='income_marks', to='app.order')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='app.supplier'),
        ),
    ]
