# Generated by Django 6.0.6 on 2026-07-27 10:15

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_seed_finance_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='income',
            name='is_credit',
            field=models.BooleanField(default=False, help_text='Sold on credit — money not received yet.'),
        ),
        migrations.AddField(
            model_name='income',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='app.buyer'),
        ),
        migrations.CreateModel(
            name='IncomePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Received from the buyer.', max_digits=12)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='MFS/cash-out charge deducted from it.', max_digits=12)),
                ('account', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.income')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
