# Generated by Django 6.0.6 on 2026-07-27 11:13

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_buyer_income_is_credit_income_buyer_incomepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomepayment',
            name='income',
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('payable', 'We paid a supplier'), ('receivable', 'A buyer paid us')], max_length=12)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, help_text='What changed hands between the two parties — this is what moves the balance.', max_digits=12)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='MFS/transfer charge. Real money, but it never touches the balance.', max_digits=12)),
                ('account', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_payments', to='app.buyer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_payments', to='app.supplier')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.DeleteModel(
            name='ExpensePayment',
        ),
        migrations.DeleteModel(
            name='IncomePayment',
        ),
    ]
