# Generated by Django 6.0.6 on 2026-07-30 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_remove_incomepayment_income_creditpayment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsignmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignment_id', models.CharField(db_index=True, max_length=64)),
                ('invoice', models.CharField(blank=True, max_length=64)),
                ('notification_type', models.CharField(max_length=32)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('tracking_message', models.TextField(blank=True)),
                ('cod_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('event_time', models.CharField(blank=True, max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('extra', models.ForeignKey(blank=True, help_text='Set when the parcel is an additional consignment, not the primary', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.extraconsignment')),
                ('order', models.ForeignKey(blank=True, help_text='Blank only if the consignment id matched nothing we booked', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consignment_events', to='app.order')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
                'indexes': [models.Index(fields=['consignment_id', 'received_at'], name='app_consign_consign_9c5fd8_idx')],
            },
        ),
    ]
