# Generated by Django 6.0.6 on 2026-08-01 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_staffprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('method', models.CharField(max_length=8)),
                ('path', models.CharField(max_length=200)),
                ('section', models.CharField(blank=True, max_length=32)),
                ('status_code', models.PositiveSmallIntegerField(default=0)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Request body, secrets redacted and truncated.')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['section', '-created_at'], name='app_adminau_section_c86304_idx')],
            },
        ),
    ]
