# Generated by Django 6.0.6 on 2026-08-01 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_adminauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Whose device this is. Null = registered before staff accounts existed; treated as the owner, so it still gets everything.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
