# Generated by Django 6.0.6 on 2026-08-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_adminpresence'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('colour', models.CharField(choices=[('slate', 'Grey'), ('red', 'Red'), ('amber', 'Amber'), ('emerald', 'Green'), ('blue', 'Blue'), ('violet', 'Violet'), ('plum', 'Plum')], default='slate', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='orders', to='app.ordertag'),
        ),
    ]
