# Generated by Django 6.0.6 on 2026-08-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_ordertag_order_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraconsignment',
            name='missing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='consignment_missing',
            field=models.BooleanField(default=False),
        ),
    ]
