# Generated by Django 6.0.6 on 2026-08-20 05:21

import app.models
from django.db import migrations, models

HELP = ("Clock time the money moved. Blank on payments recorded before times "
        "were kept.")


class Migration(migrations.Migration):
    """Add the clock time a credit payment was made.

    Two steps on purpose. A single AddField carrying the callable default would
    evaluate it once and stamp EVERY historical payment with the moment this
    migration ran — a fabricated time, indistinguishable from a real one. The
    column is added bare so old rows stay NULL (the API falls back to
    `created_at` for them), and the default is attached afterwards so it only
    ever applies to rows written from now on.
    """

    dependencies = [
        ('app', '0042_extraconsignment_missing_order_consignment_missing'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpayment',
            name='time',
            field=models.TimeField(blank=True, null=True, help_text=HELP),
        ),
        migrations.AlterField(
            model_name='creditpayment',
            name='time',
            field=models.TimeField(blank=True, null=True, help_text=HELP,
                                   default=app.models.local_clock_time),
        ),
    ]
